default: &default
  fcm_server_key: <%= ENV['HAIRFOLIO_FCM_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
